/*****************************************************************************
* Model: cdb_usb.qm
* File:  ./bsp.h
*
* This code has been generated by QM tool (see state-machine.com/qm).
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*****************************************************************************/
/*${.::bsp.h} ..............................................................*/
#ifndef bsp_h
#define bsp_h

#include <stdint.h>

#define BSP_TICKS_PER_SEC    100U

/* hardware trigger PORTB.14 */

#define TRG_ON() _RB14 = 1
#define TRG_OFF() _RB14 = 0

//#define LED_ON()                (LATD |= (1U << 2))
//#define LED_OFF()               (LATD &= ~(1U << 2))
//#define LED_TOGGLE()            (LATD ^= (1U << 2))

#define LED_ON() _RD2 = 1
#define LED_OFF() _RD2 = 0

/* VBUS power switch control pin  PORTF.3*/
/* MIC2004 turns on by high level */
#define VBUS_ON()    _RF3 = 1
#define VBUS_OFF()   _RF3 = 0


/* Public board-related functions */

/*${BSP::BSP_init} .........................................................*/
void BSP_init(void);

/*${BSP::Console_printStr} .................................................*/
void Console_printStr(const char* str);

/*${BSP::Console_printNum} .................................................*/
void Console_printNum(uint32_t num, uint8_t base);

/*${BSP::Console_printRoll} ................................................*/
void Console_printRoll(void);


#endif
