/*****************************************************************************
* Model: cdb_usb.qm
* File:  ./cdb_usb.h
*
* This code has been generated by QM tool (see state-machine.com/qm).
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*****************************************************************************/
/*${.::cdb_usb.h} ..........................................................*/
#ifndef a1tester_h
#define a1tester_h

//#include "qp_port.h"

#include <stdint.h>
#include <stdbool.h>
#include <p24FJ256GB206.h>                /* header for PIC24F device in use */

#include "usbsie_p24f.h"


enum CdbUsbSignals {
    /* CLI */
    USB_DEV_ATTACH_SIG = Q_USER_SIG,
    USB_DEV_DETACH_SIG,
    PRINT_STRING_SIG,
    MAX_PUB_SIG,
    MENU_SELECT_SIG,
    ROLL_SIG,
    BLINK_SIG,
    MAX_SIG
};


/*${Events::MenuSelectEvt} .................................................*/
typedef struct {
/* protected: */
    QEvt super;

/* public: */
    uint8_t key;
} MenuSelectEvt;

/*${Events::PrintStringEvt} ................................................*/
typedef struct {
/* protected: */
    QEvt super;

/* public: */
    const char* str;
} PrintStringEvt;



/*${AOs::CLI_ctor} .........................................................*/
void CLI_ctor(void);

/*${AOs::USBTask_ctor} .....................................................*/
void USBTask_ctor(void);



extern QActive* const AO_CLI;

extern QActive* const AO_USBTask;



#endif    //cdb_minimal_h
