/*****************************************************************************
* Model: cdb_usb.qm
* File:  ./cli.c
*
* This code has been generated by QM tool (see state-machine.com/qm).
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*****************************************************************************/
/*${.::cli.c} ..............................................................*/
#include "qp_port.h"
#include "cdb_usb.h"
#include "bsp.h"

Q_DEFINE_THIS_FILE

/* Menus */

const char* menuMain[]={"Do Something", "Do Something Else", "Rest"};
#define MENU_MAIN_CNT Q_DIM(menuMain)


/*${AOs::CLI} ..............................................................*/
typedef struct {
/* protected: */
    QActive super;

/* private: */
    QTimeEvt blinkEvt;
    QTimeEvt rollEvt;
} CLI;

/* private: */
static void CLI_printMenuTitles(CLI * const me, uint8_t count, const char** menu);

/* protected: */
static QState CLI_initial(CLI * const me, QEvt const * const e);
static QState CLI_main(CLI * const me, QEvt const * const e);
static QState CLI_idle(CLI * const me, QEvt const * const e);
static QState CLI_menu_Top(CLI * const me, QEvt const * const e);


static CLI l_cli;    //storage


/* Time intervals for AO timers */
#define BLINK_ON_TIME    1    //ticks
#define BLINK_OFF_TIME   250

#define ROLL_TIME 10


QActive* const AO_CLI = &l_cli.super;    /* Opaque AO pointer */

/*${AOs::CLI_ctor} .........................................................*/
void CLI_ctor(void) {
    CLI* me = &l_cli;

    QActive_ctor( &me->super, Q_STATE_CAST( &CLI_initial ));
    QTimeEvt_ctor( &me->blinkEvt, BLINK_SIG );
    QTimeEvt_ctor( &me->rollEvt, ROLL_SIG );
}
/*${AOs::CLI} ..............................................................*/
/*${AOs::CLI::printMenuTitles} .............................................*/
static void CLI_printMenuTitles(CLI * const me, uint8_t count, const char** menu) {
     uint8_t i;
     const char* const crlf="\r\n";

        Console_printStr(/*(char*)*/crlf );

        for( i=0; i<=count; i++ ) {

            Console_printNum(i, 10 );
            Console_printStr(". " );

            if (i == 0) {
              Console_printStr("Back" );
            }
            else {
                Console_printStr((char*)menu[i-1] );
             }

            Console_printStr((char*)crlf );
        }


        Console_printStr((char*)crlf );
}
/*${AOs::CLI::SM} ..........................................................*/
static QState CLI_initial(CLI * const me, QEvt const * const e) {
    /* ${AOs::CLI::SM::initial} */
    /* Print banner on the serial console */

        Console_printStr("\r\nStart\r\n");
        Console_printStr("Compiled on ");
        Console_printStr(__DATE__);
        Console_printStr(" at ");
        Console_printStr(__TIME__);
        Console_printStr(" using Microchip XC16 ver.");
        Console_printNum(__XC16_VERSION__, 10);

        LED_ON();

        QTimeEvt_postIn( &me->blinkEvt, (QActive *)me, BLINK_ON_TIME );

    QActive_subscribe((QActive *)me, PRINT_STRING_SIG);
    return Q_TRAN(&CLI_idle);
}
/*${AOs::CLI::SM::main} ....................................................*/
static QState CLI_main(CLI * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /* ${AOs::CLI::SM::main::BLINK} */
        case BLINK_SIG: {
            static bool on_off = false;

            uint8_t time;

            if( on_off == true ) {
                LED_ON();
                time = BLINK_ON_TIME;
            } else {
                LED_OFF();
                time = BLINK_OFF_TIME;
            }

            on_off = !on_off;
            QTimeEvt_postIn( &me->blinkEvt, (QActive *)me, time );
            status_ = Q_HANDLED();
            break;
        }
        /* ${AOs::CLI::SM::main::MENU_SELECT} */
        case MENU_SELECT_SIG: {
            status_ = Q_TRAN(&CLI_menu_Top);
            break;
        }
        /* ${AOs::CLI::SM::main::PRINT_STRING} */
        case PRINT_STRING_SIG: {
            Console_printStr( ((PrintStringEvt const*)e)->str );
            status_ = Q_HANDLED();
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}
/*${AOs::CLI::SM::main::idle} ..............................................*/
static QState CLI_idle(CLI * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /* ${AOs::CLI::SM::main::idle} */
        case Q_ENTRY_SIG: {
            QTimeEvt_postEvery( &me->rollEvt, (QActive *)me, ROLL_TIME );
            Console_printStr("\r\r\n\nPress any key to continue...");
            status_ = Q_HANDLED();
            break;
        }
        /* ${AOs::CLI::SM::main::idle} */
        case Q_EXIT_SIG: {
            QTimeEvt_disarm(&me->rollEvt);
            status_ = Q_HANDLED();
            break;
        }
        /* ${AOs::CLI::SM::main::idle::ROLL} */
        case ROLL_SIG: {
            Console_printRoll();
            status_ = Q_HANDLED();
            break;
        }
        default: {
            status_ = Q_SUPER(&CLI_main);
            break;
        }
    }
    return status_;
}
/*${AOs::CLI::SM::main::menu_Top} ..........................................*/
static QState CLI_menu_Top(CLI * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /* ${AOs::CLI::SM::main::menu_Top} */
        case Q_ENTRY_SIG: {
            Console_printStr("\r\nTop Menu\r\n");
            CLI_printMenuTitles((CLI*)me, MENU_MAIN_CNT, menuMain );
            status_ = Q_HANDLED();
            break;
        }
        default: {
            status_ = Q_SUPER(&CLI_main);
            break;
        }
    }
    return status_;
}

