/*****************************************************************************
* Model: cdb_usb.qm
* File:  ./usbtask.c
*
* This code has been generated by QM tool (see state-machine.com/qm).
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*****************************************************************************/
/*${.::usbtask.c} ..........................................................*/
#include "qp_port.h"
#include "cdb_usb.h"
#include "bsp.h"

Q_DEFINE_THIS_FILE

/* Menus */


/*${AOs::USBTask} ..........................................................*/
typedef struct {
/* protected: */
    QActive super;
} USBTask;

/* protected: */
static QState USBTask_initial(USBTask * const me, QEvt const * const e);
static QState USBTask_main(USBTask * const me, QEvt const * const e);
static QState USBTask_idle(USBTask * const me, QEvt const * const e);


static USBTask l_usbtask;    //storage


/* Time intervals for AO timers */
//#define BLINK_ON_TIME    1    //ticks
//#define BLINK_OFF_TIME   250

//#define ROLL_TIME 10


QActive* const AO_USBTask = &l_usbtask.super;    /* Opaque AO pointer */

/*${AOs::USBTask_ctor} .....................................................*/
void USBTask_ctor(void) {
    USBTask* me = &l_usbtask;

    QActive_ctor( &me->super, Q_STATE_CAST( &USBTask_initial ));
    //QTimeEvt_ctor( &me->blinkEvt, BLINK_SIG );
    //QTimeEvt_ctor( &me->rollEvt, ROLL_SIG );
}
/*${AOs::USBTask} ..........................................................*/
/*${AOs::USBTask::SM} ......................................................*/
static QState USBTask_initial(USBTask * const me, QEvt const * const e) {
    /* ${AOs::USBTask::SM::initial} */
    /**/
    QActive_subscribe((QActive *)me, USB_DEV_ATTACH_SIG);
    QActive_subscribe((QActive *)me, USB_DEV_DETACH_SIG);

    VBUS_ON();
    return Q_TRAN(&USBTask_idle);
}
/*${AOs::USBTask::SM::main} ................................................*/
static QState USBTask_main(USBTask * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /* ${AOs::USBTask::SM::main::USB_DEV_ATTACH} */
        case USB_DEV_ATTACH_SIG: {
             const char* const udastr = "\r\nUSB device attached  ";
             PrintStringEvt* pse = Q_NEW(PrintStringEvt, PRINT_STRING_SIG);

                    pse->str = udastr;
                    QF_PUBLISH((QEvt*)pse, &me );

                    _DETACHIE = 1;
            status_ = Q_HANDLED();
            break;
        }
        /* ${AOs::USBTask::SM::main::USB_DEV_DETACH} */
        case USB_DEV_DETACH_SIG: {
            const char* const uddstr = "\r\nUSB device detached  ";
            PrintStringEvt* pse = Q_NEW(PrintStringEvt, PRINT_STRING_SIG);

                    pse->str = uddstr;
                    QF_PUBLISH((QEvt*)pse, &me );

            status_ = Q_TRAN(&USBTask_idle);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}
/*${AOs::USBTask::SM::main::idle} ..........................................*/
static QState USBTask_idle(USBTask * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /* ${AOs::USBTask::SM::main::idle} */
        case Q_ENTRY_SIG: {
                _ATTACHIE = 1;
            status_ = Q_HANDLED();
            break;
        }
        /* ${AOs::USBTask::SM::main::idle} */
        case Q_EXIT_SIG: {
                _DETACHIE = 1;
            status_ = Q_HANDLED();
            break;
        }
        default: {
            status_ = Q_SUPER(&USBTask_main);
            break;
        }
    }
    return status_;
}

